version: '2'
services:
  vnsd-postgresql:
    image: postgres:11.4
    # volumes:
    #     - ~/volumes/jhipster/vnsd/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=vnsd
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
